config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users, only: :show do
        resources :posts, only: [:index], shallow: true do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  get "/posts/new", to: "posts#new", as: :new_post
  post "/posts/create", to: "posts#create", as: :posts
  post "/users/:user_id/posts/:id/like_a_post", to: "likes#like_a_post", as: :like_a_post
  post "/users/:user_id/posts/:id/comment_a_post", to: "comments#comment_a_post", as: :comment_a_post
  delete "/users/:user_id/posts/:id", to: "posts#destroy", as: :delete_post

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :create, :all
    can :destroy, Post do |post|
      post.author == user
    end

    can :destroy, Comment do |comment|
      comment.author == user
    end

    return unless user.role == 'admin'

    can :manage, :all
    can :destroy, Post
    can :destroy, Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :increment_comment
  after_destroy :decrement_comment

  def increment_comment
    post.increment!(:comments_counter)
  end

  def decrement_comment
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :increment_like

  def increment_like
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :increment_post

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_five_comments
    comments.order(created_at: :desc).limit(5)
  end

  def increment_post
    author.increment!(:posts_counter)
  end

  def decrement_post
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy
  before_validation :initial_number, on: :create
  before_create :set_user_token

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_three_posts
    posts.order(created_at: :desc).limit(3)
  end

  def initial_number
    self.posts_counter = 0
  end

  def set_user_token
    self.user_token = SecureRandom.hex(20)
  end

  def all_posts
    posts.includes(:comments, comments: :author)
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  before_action :authenticate

  def authenticate
    token = request.headers['Authorization']
    @current_user = User.find_by(auth_token: token)

    render json: { error: 'Not Authorized' }, status: 401 unless current_user
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::BaseController
  def index
    post = Post.find(params[:post_id])
    @comments = Comment.where(post:)

    render json: @comments
  end

  def create
    @new_comment = Comment.new(params.require(:comment).permit(:post_id, :text))
    @new_comment.post_id = params[:post_id]
    @new_comment.author = @authorized_user

    if @new_comment.save
      render json: @new_comment, status: :created
    else
      render json: @new_comment.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
  skip_before_action :authenticate, only: :index

  def index
    @posts = Post.where(author: User.find(params[:user_id]))

    render json: @posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery unless: -> { request.format.json? }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user, only: :index
  before_action :set_likes, only: :index

  def comment_a_post
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.author = current_user
    @comment.post = Post.find(params[:id])
    if @comment.save
      redirect_to "/users/#{params[:user_id]}/posts/#{params[:id]}", notice: 'Comment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post

    @comment.destroy
    redirect_back(fallback_location: post)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like_a_post
    @like = Like.new(author: current_user, post: Post.find(params[:id]))
    if @like.save
      redirect_to "/users/#{params[:user_id]}/posts/#{params[:id]}", notice: 'You Liked this post!'
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.all_posts
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    user = @post.author

    @post.destroy
    redirect_to user_posts_path(user)
  end

  def post_params
    params.require(:post).permit(:title, :text, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.last_three_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class="wrapper">
  <div class="users">
    <div class="user-img">

          <% if @user&.photo%>
      <%= image_tag @user.photo %>
      <% end %>
    </div>
    <div class="user-infos">
      <p class="u-name"> <%= @user.name %> </p>
      <div class="u-counter-wrapper">
        Number of posts: <div class="tag">
        <p class="u-counter"> <%= @user.posts_counter %> </p>
        </div>
      </div>
    </div>
  </div>

  <div class="">
    <% @posts.each do |post| %>
    <div class="each-post">
    <div class="post-wrapper">
    <div class="post-head">
      <h2> Post by <%= @user.name %> </h2>
      <div class="com-like">
        <span class="com">Comments: <%= post.comments.count %> | </span>
        <span class="like">Likes: <%= post.likes.count %></span>
      </div>

    </div>
    <p><%= post.text %></p>


      <% if can? :destroy, post %>
      <p class='text-end'><%= button_to 'Delete', user_post_path(@user, post), method: :delete %></p>
      <% end %>
    </div>



    <% if !post.last_five_comments.empty? %>
    <section class="comment-wrapper">
      <% post.last_five_comments.each do |comment| %>
        <div class="comment">
          <p> <%= comment.author.name %> : <%= comment.text %></p>
        </div>
      <% end %>
    </section>
    <% end %>
    </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<section class="wrapper">
  <%= link_to "/users", remote: false do %>
    <span class="">back arrow_back_ios</span>
  <% end %>

  <div class="new-post-wrapper">
    <h2>New blod</h2>
  </div>

  <div class="form-wrapper">
    <%= form_with model: @post do |form| %>
      <% if form.object.errors.any? %>
        <div>
          <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>
      <div class="field">
        <%= form.label :text %>
        <%= form.text_area :text %>
      </div>
      <%= form.button %>
    <% end %>
  </div>
</section>

app/views/posts/show.html.erb
<section class="wrapper">
  <div class="post-wrapper">
  <div class="post-head">
    <h2> Post by <%= @user.name %> </h2>
    <div class="com-like">
      <span class="com">Comments: <%= @post.comments.count %> | </span>
      <span class="like">Likes: <%= @post.likes.count %></span>
    </div>
  </div>
  <p><%= @post.text %></p>

  <div class="like-post-wrapper">
    <%= form_with(url: "/users/#{params[:user_id]}/posts/#{@post.id}/like_a_post", method: :post) do |form| %>
      <div class="btn-like-wrapper">
        <%= form.submit 'Like', :class => 'btn-like' %>
      </div>
    <% end %>

  </div>
  </div>


  <div class="add-comment-wrapper">
    <%= form_with url: "/users/#{params[:user_id]}/posts/#{@post.id}/comment_a_post", method: :post, local: true, scope: :comment do |f| %>
        <div class="c-input-wrapper">
          <p>Add a comment:</p>
          <%= f.text_area :text,  :maxlength => 250, :class => 'c-input' %>
        </div>
        <%= f.submit "Add a comment", class: 'btn-comment'%>
    <% end %>
  </div>

  <% if !@post.comments.empty? %>
  <section class="comment-wrapper">
    <% @post.comments.each do |comment| %>
      <div class="comment">
        <p> <%= comment.author.name %> : <%= comment.text %></p>
        <p>
          <% if can? :destroy, comment %>
            <p class='text-end'><%= button_to 'Delete', user_post_comment_path(@user, @post, comment), method: :delete %></p>
          <% end %>
        </p>
      </div>
    <% end %>
  </section>
  <% end %>

</section>

app/views/users/index.html.erb
<section class="wrapper">
  <section class="users-wrapper">
    <%= link_to 'newpost', "posts/new" %>
    <h1>List of users</h1>
    <% @users.each do |user| %>
      <%= link_to "users/#{user.id}", remote: false do %>
      <div class="users">
        <div class="user-img">
          <% if user&.photo%>
            <%= image_tag user.photo %>
          <% end %>
        </div>
        <div class="user-infos">
          <p class="u-name"> <%= user.name %> </p>
          <div class="u-counter-wrapper">
            Number of posts: <div class="tag">
            <p class="u-counter"> <%= user.posts_counter %> </p>
            </div>
          </div>
        </div>
      </div>
      <%end%>
    <% end %>
  </section>
</section>

app/views/users/show.html.erb
<section class="wrapper">
  <section class="users-wrapper">
    <h1>User</h1>
    <div class="users">
      <div class="user-img">

          <% if @user&.photo%>
        <%= image_tag @user.photo %>
        <% end %>
      </div>
      <div class="user-infos">
        <p class="u-name"> <%= @user.name %> </p>
        <div class="u-counter-wrapper">
          Number of posts: <div class="tag">
          <p class="u-counter"> <%= @user.posts_counter %> </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="u-bio">
    <h1>Biography</h1>
    <div class="u-bio-text-wrapper">
      <p class="u-bio-text"> <%= @user.bio %> </p>
    </div>
  </section>

  <section class="three-last-post">
    <h1>Three last posts</h1>
    <% @posts.each do |post| %>
      <%= link_to "/users/#{@user.id}/posts/#{post.id}" do %>
        <div class="u-post">
          <div class="u-post-infos">
            <p class="u-p-title"> <%= post.title %> </p>
            <p class="u-p-text"> <%= post.text %> </p>
            <div class="date-stat">
              <p class="u-p-date"> <%= post.created_at.strftime("%d/%m/%Y") %> </p>
              <div class="stat">
                <p> Likes:  <%= post.likes_counter %> | </p>
                <p>  Comments: <%= post.comments_counter %> </p>
              </div>
            </div>
          </div>
          <div class="u-com-li">
          </div>
        </div>
      <% end %>
    <% end %>
  </section>

  <div class="btn-all-wrapper">
    <button>
      <%= link_to 'See all post', "/users/#{@user.id}/posts" %>
    </button>
  </div>
</section>